name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: 'temurin'

jobs:



  Lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v5

      - run: ./gradlew ktlintFormat --stacktrace
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Ktlint format



  Build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v5

      - run: ./gradlew build --stacktrace
